import Foundation
import SwiftUI

@MainActor
class AnalysisViewModel: ObservableObject {
    @Published var urlInput: String = ""
    @Published var isLoading = false
    @Published var currentResult: AnalysisResult?
    @Published var error: String?
    @Published var history: [AnalysisResult] = []
    @Published var showingHistory = false
    
    private let apiService = APIService.shared
    private let historyService = HistoryService.shared
    
    init() {
        loadHistory()
    }
    
    func analyzeApp() async {
        guard !urlInput.isEmpty else {
            error = "Please enter a URL"
            return
        }
        
        isLoading = true
        error = nil
        
        do {
            let result = try await apiService.analyzeApp(url: urlInput)
            currentResult = result
            historyService.saveResult(result)
            loadHistory()
            HapticFeedback.success.trigger()
        } catch {
            self.error = error.localizedDescription
            HapticFeedback.error.trigger()
        }

        isLoading = false
    }
    
    func recheckApp() async {
        await analyzeApp()
    }
    
    func reset() {
        currentResult = nil
        error = nil
        urlInput = ""
    }
    
    func loadHistory() {
        history = historyService.getHistory()
    }
    
    func deleteHistoryItem(id: String) {
        historyService.deleteResult(id: id)
        loadHistory()
    }
    
    func clearHistory() {
        historyService.clearHistory()
        loadHistory()
    }
    
    func shareReport() -> String {
        guard let result = currentResult else { return "" }
        
        var report = """
        Dead App Detector Analysis Report
        
        URL: \(result.url)
        Date: \(formatDate(result.timestamp))
        Overall Score: \(result.overallScore)/100
        Status: \(result.status.displayName)
        
        Summary:
        \(result.summary)
        
        Website Signals (Score: \(result.categories.website.score)/100):
        """
        
        for signal in result.categories.website.signals {
            report += "\n• \(signal.name): \(signal.value) - \(signal.explanation)"
        }
        
        report += "\n\nEngineering Signals (Score: \(result.categories.engineering.score)/100):"
        for signal in result.categories.engineering.signals {
            report += "\n• \(signal.name): \(signal.value) - \(signal.explanation)"
        }
        
        report += "\n\nBusiness Signals (Score: \(result.categories.business.score)/100):"
        for signal in result.categories.business.signals {
            report += "\n• \(signal.name): \(signal.value) - \(signal.explanation)"
        }
        
        report += "\n\nGenerated by Dead App Detector"
        
        return report
    }
    
    private func formatDate(_ isoDate: String) -> String {
        return isoDate.formatISO8601Date(style: .medium)
    }
}
